// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jordanlanch/bia-test/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MeterRepository is an autogenerated mock type for the MeterRepository type
type MeterRepository struct {
	mock.Mock
}

// FindById provides a mock function with given fields: ctx, id
func (_m *MeterRepository) FindById(ctx context.Context, id uuid.UUID) (*domain.Meter, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Meter
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Meter); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Meter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMany provides a mock function with given fields: ctx, pagination
func (_m *MeterRepository) FindMany(ctx context.Context, pagination *domain.Pagination) ([]*domain.Meter, error) {
	ret := _m.Called(ctx, pagination)

	var r0 []*domain.Meter
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Pagination) []*domain.Meter); ok {
		r0 = rf(ctx, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Meter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Pagination) error); ok {
		r1 = rf(ctx, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMeterRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMeterRepository creates a new instance of MeterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMeterRepository(t mockConstructorTestingTNewMeterRepository) *MeterRepository {
	mock := &MeterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
